CREATE TABLE TB_BILL_DETAIL
(
  ID NUMBER NOT NULL 
, BILL_ID NUMBER NOT NULL
, PRODUCT_ID NUMBER NOT NULL
, QUANTITY NUMBER NOT NULL 
, CONSTRAINT TB_BILL_DETAIL_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

/* CREATE FOREIGN KEYS */
ALTER TABLE TB_BILL_DETAIL ADD CONSTRAINT FK_BILLDETAIL_BILL FOREIGN KEY (BILL_ID) REFERENCES TB_BILLS(ID);
ALTER TABLE TB_BILL_DETAIL ADD CONSTRAINT FK_BILLDETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCTS(ID);

/* CREATE A SEQUENCE FOR ID */
CREATE SEQUENCE BILL_DETAIL_ID_SEQ;

/* FOR BILL 1 */
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 1, 21, 4);
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 1, 22, 5);
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 1, 23, 6);
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 1, 24, 7);

/* FOR BILL 2 */
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 2, 25, 10);
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 2, 21, 3);
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 2, 24, 8);
INSERT INTO TB_BILL_DETAIL (ID, BILL_ID, PRODUCT_ID, QUANTITY)
VALUES (BILL_DETAIL_ID_SEQ.nextval, 2, 22, 1);


