CREATE TABLE TB_BILLS 
(
  ID NUMBER NOT NULL 
, USER_ID NUMBER NOT NULL 
, DISCCOUNT NUMBER DEFAULT 0 
, TOTAL NUMBER NOT NULL 
, COMMENTS VARCHAR2(20) 
, CONSTRAINT TB_BILLS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


/* CREATE FOREIGN KEYS */
ALTER TABLE TB_BILLS ADD CONSTRAINT FK_BILLS_USERS FOREIGN KEY (USER_ID) REFERENCES TB_USERS(ID);


/* CREATE A SEQUENCE FOR ID */
CREATE SEQUENCE BILL_ID_SEQ;

INSERT INTO TB_BILLS (ID, USER_ID, DISCCOUNT, TOTAL, COMMENTS)
VALUES (BILL_ID_SEQ.nextval, 1, 0, 10500, 'BILL 1 DESCRIPTION');
INSERT INTO TB_BILLS (ID, USER_ID, DISCCOUNT, TOTAL, COMMENTS)
VALUES (BILL_ID_SEQ.nextval, 2, 1200, 23700, 'BILL 2 DESCRIPTION');